version: "3.8"
services:
  backend:
  frontend:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    
    environment:
      MONGO_INITDB_ROOT_USERNAME : max
      MONGO_INITDB_ROOT_PASSWORD : secret